lib/kazarma_web/router.ex
defmodule KazarmaWeb.Router do
  use KazarmaWeb, :router

  use MatrixAppServiceWeb.Routes
  use ActivityPubWeb.Router

  # pipeline :api do
  #   plug :accepts, ["json"]
  # end

  # scope "/api", KazarmaWeb do
  #   pipe_through :api
  # end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session

    plug Cldr.Plug.SetLocale,
      apps: [cldr: KazarmaWeb.Cldr, gettext: KazarmaWeb.Gettext],
      from: [:query, :path, :body, :cookie, :accept_language],
      param: "locale"

    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", KazarmaWeb do
    pipe_through :browser

    get "/", IndexController, :index

    post "/search", SearchController, :search
  end

  MatrixAppServiceWeb.Routes.routes(
    base_url: :config,
    access_token: :config,
    homeserver_token: :config,
    transaction_adapter: Kazarma.Matrix.Transaction,
    room_adapter: Kazarma.Matrix.Room,
    user_adapter: Kazarma.Matrix.User,
    path: "/matrix"
  )

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:fetch_session, :protect_from_forgery]
      live_dashboard "/dashboard", metrics: KazarmaWeb.Telemetry
    end
  end
end

lib/kazarma_web/views/layout_view.ex
defmodule KazarmaWeb.LayoutView do
  use KazarmaWeb, :view
end

lib/kazarma_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Kazarma</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="fixed w-full z-10 top-0">
      <div class="navbar mb-2 shadow-lg justify-between">
        <div class="flex-none px-2 mx-2 lg:flex">
          <%= link [to: Routes.index_path(@conn, :index), class: "text-2xl font-bold"], do: "Kazarma" %>
        </div>
        <%= if Application.get_env(:kazarma, :html_search, false) do %>
          <div class="flex-grow lg:max-w-3xl mt-0 lg:absolute lg:mx-auto lg:inset-x-0">
            <%= form_for @conn, Routes.search_path(@conn, :search), [as: :search, class: "w-full"], fn f -> %>
              <div class="flex flex-row items-center justify-between space-x-2">
                <div class="flex-1 space-x-2">
                  <div class="form-control">
                    <%= text_input f, :address, aria_label: gettext("Matrix or ActivityPub username, or ActivityPub ID"), placeholder: gettext("@alice:matrix.org / bob@mastodon.social / https://mastodon.social/users/bob"), class: "w-full input input-bordered" %>
                  </div>
                </div>
                <div class="flex-none">
                  <%= submit [aria_label: gettext("Search"), title: gettext("Search"), class: "btn btn-outline"], do: KazarmaWeb.IconView.search_icon() %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="flex-none px-2 mx-2 lg:flex">
          <%= link [to: "https://gitlab.com/kazarma/kazarma", target: "_blank", aria_label: gettext("GitLab repository"), title: gettext("GitLab repository"), class: "text-2xl font-bold"], do: KazarmaWeb.IconView.gitlab_icon() %>
        </div>
      </div>
    </header>
    <main role="main" class="container w-full lg:max-w-3xl mx-auto pt-20">
      <p class="alert alert-info mb-2" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-error mb-2" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>